# Generated by Django 4.1.1 on 2022-10-21 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.ForeignKey(on_delete=models.SET('User Deleted'), related_name='initiated_relations', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=models.SET('User Deleted'), related_name='received_relations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
