# Generated by Django 4.1.1 on 2022-10-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_alter_relations_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relations',
            unique_together={('initiator', 'receiver')},
        ),
    ]
